site_name: Documention by Christian Pillajo Sanchez

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  
plugins:
  - search
  - mkdocstrings


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/COPS95
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/christianpillajosanchez/


copyright: |
  &copy; 2024 <a href="https://github.com/COPS95"  target="_blank" rel="noopener">Christian Pillajo Sanchez</a>