version: 1
disable_existing_loggers: false
formatters:
  text:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  json:
    format: "{\"timestamp\": \"%(asctime)s\", \"name\": \"%(name)s\", \"level\": \"%(levelname)s\", \"message\": %(message)s}"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: text
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    filename: logs/app.log
    maxBytes: 5485760
    backupCount: 5
    formatter: text
root:
  level: INFO
  handlers: [console, file]